runtime: python311
service: default-django

entrypoint: gunicorn -b :$PORT my_site.wsgi

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: 'my_site.settings'